In [18]:
from numpy import array
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Flatten,Embedding,Dense,LSTM

In [19]:
# Define 10 restaurant reviews
reviews =[
          'Never coming back!',
          'horrible service',
          'rude waitress',
          'cold food',
          'horrible food!',
          'awesome',
          'awesome services!',
          'rocks',
          'poor work',
          'couldn\'t have done better'
]
#Define labels
labels = array([1,1,1,1,1,0,0,0,0,0])

In [20]:
Vocab_size = 50
encoded_reviews = [one_hot(d,Vocab_size) for d in reviews]
print(f'encoded reviews: {encoded_reviews}')

encoded reviews: [[39, 18, 49], [16, 7], [34, 31], [45, 46], [16, 46], [1], [1, 45], [18], [25, 40], [44, 1, 5, 5]]


In [21]:
max_length = 4
padded_reviews = pad_sequences(encoded_reviews,maxlen=max_length,padding='post')
print(padded_reviews)

[[39 18 49  0]
 [16  7  0  0]
 [34 31  0  0]
 [45 46  0  0]
 [16 46  0  0]
 [ 1  0  0  0]
 [ 1 45  0  0]
 [18  0  0  0]
 [25 40  0  0]
 [44  1  5  5]]


In [27]:
model = Sequential()
embedding_layer = Embedding(input_dim=Vocab_size,output_dim=8,input_length=max_length)
model.add(embedding_layer)
model.add(LSTM(50, dropout=0.2, recurrent_dropout=0.2))
#model.add(Flatten())
model.add(Dense(1,activation='sigmoid'))
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['acc'])
print(model.summary())

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_3 (Embedding)     (None, 4, 8)              400       
                                                                 
 lstm_1 (LSTM)               (None, 50)                11800     
                                                                 
 dense_3 (Dense)             (None, 1)                 51        
                                                                 
Total params: 12,251
Trainable params: 12,251
Non-trainable params: 0
_________________________________________________________________
None


In [28]:
model.fit(padded_reviews,labels,epochs=100,verbose=1)

Epoch 1/100
1/1 [==============================] - 4s 4s/step - loss: 0.6920 - acc: 0.6000
Epoch 2/100
1/1 [==============================] - 0s 27ms/step - loss: 0.6925 - acc: 0.7000
Epoch 3/100
1/1 [==============================] - 0s 18ms/step - loss: 0.6923 - acc: 0.5000
Epoch 4/100
1/1 [==============================] - 0s 20ms/step - loss: 0.6909 - acc: 0.7000
Epoch 5/100
1/1 [==============================] - 0s 20ms/step - loss: 0.6897 - acc: 1.0000
Epoch 6/100
1/1 [==============================] - 0s 16ms/step - loss: 0.6899 - acc: 1.0000
Epoch 7/100
1/1 [==============================] - 0s 17ms/step - loss: 0.6902 - acc: 0.9000
Epoch 8/100
1/1 [==============================] - 0s 16ms/step - loss: 0.6889 - acc: 0.9000
Epoch 9/100
1/1 [==============================] - 0s 16ms/step - loss: 0.6902 - acc: 0.9000
Epoch 10/100
1/1 [==============================] - 0s 16ms/step - loss: 0.6896 - acc: 0.8000
Epoch 11/100
1/1 [==============================] - 0s 15ms/step - loss

In [24]:
print(embedding_layer.get_weights()[0].shape)

(50, 8)


In [30]:
print(model.predict(padded_reviews)[3])

1/1 [==============================] - 0s 25ms/step
[0.98601276]
